# PyTorch for Beginners


In [1]:
# Libraries and Frameworks

import numpy as np
import torch

### 1. Basics of PyTorch Tensors

In [2]:
#1.1 Basics of PyTorch Tensors

a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(a.shape)
print(a.dtype)
print(a.device)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
torch.int64
cpu


In [3]:
#1.2 Special Tensors

b = torch.zeros((3, 3))
print("This is like a zeroes matrix/Tensor",b)
print(b.shape)
c = torch.ones((3, 3))
print("This is like a ones matrix/Tensor", c)
print(c.shape)
d = torch.eye(3)
print("This is like an identity matrix/Tensor", d)
print(d.shape)

This is like a zeroes matrix/Tensor tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])
This is like a ones matrix/Tensor tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([3, 3])
This is like an identity matrix/Tensor tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.Size([3, 3])


In [4]:
#1.3 Accessing element of a tensor

print("First element of a tensor:", a[0][0])
print("Fifth element of a tensor:", a[1][1])
print("Last element of a tensor:", a[-1][-1])


First element of a tensor: tensor(1)
Fifth element of a tensor: tensor(5)
Last element of a tensor: tensor(9)


In [5]:
#1.4 Slicing a tensor

print("First row of a tensor", a[0:1])
print("First column of a tensor", a[:, 0])
print("Last row of a tensor", a[-1])
print("Last column of a tensor", a[:, -1])


First row of a tensor tensor([[1, 2, 3]])
First column of a tensor tensor([1, 4, 7])
Last row of a tensor tensor([7, 8, 9])
Last column of a tensor tensor([3, 6, 9])


In [6]:
# 1.5 changing data type of tensor form int to float
a.dtype
a_float = a.float()
print(a_float)
print(a_float.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.float32


In [7]:
#1.6 Converting Pytorch tensor from Numpy Array

x = np.array([[1, 5, 3], [8, 7, 6], [1, 0, 9]])
print("Numpy array x is: ", x)
x_tensor = torch.from_numpy(x)
print("Pytorch tensor x is: ", x_tensor)

Numpy array x is:  [[1 5 3]
 [8 7 6]
 [1 0 9]]
Pytorch tensor x is:  tensor([[1, 5, 3],
        [8, 7, 6],
        [1, 0, 9]])


In [8]:
#1.6 Converting Pytorch tensor to Numpy Array
print("Pytorch tensor x is: ", x_tensor)
y = x_tensor.numpy()    
print("Numpy array y is: ", y)

Pytorch tensor x is:  tensor([[1, 5, 3],
        [8, 7, 6],
        [1, 0, 9]])
Numpy array y is:  [[1 5 3]
 [8 7 6]
 [1 0 9]]


In [9]:
#1.7 Reshaping a tensor (Transpose)
a_transpose = a.T
print("Transpose of the Original tensor a is: ", a_transpose)  



Transpose of the Original tensor a is:  tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


### 2. Operations on Tensors


In [10]:
#2.1 Addition of tensors (Elementwise)

A1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A2 = torch.tensor([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
A3 = A1 + A2
print("Addition of two tensors A1 and A2 is: ", A3)

Addition of two tensors A1 and A2 is:  tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])


In [11]:
#2.2 Subtraction of tensors (Elementwise)

A4 = A2 - A1
print("Subtraction of two tensors A2 and A1 is: ", A4)

Subtraction of two tensors A2 and A1 is:  tensor([[ 8,  6,  4],
        [ 2,  0, -2],
        [-4, -6, -8]])


In [12]:
#2.3 Multiplication of tensors (Elementwise)

A5 = A1 * A2
print("Multiplication of two tensors A1 and A2 is: ", A5)

Multiplication of two tensors A1 and A2 is:  tensor([[ 9, 16, 21],
        [24, 25, 24],
        [21, 16,  9]])


In [13]:
#2.4 Matrix Multiplication of tensors

A6 = torch.matmul(A1, A2)
print("Matrix Multiplication of two tensors A1 and A2 is: ", A6)

Matrix Multiplication of two tensors A1 and A2 is:  tensor([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])


In [14]:
#2.5 Multiplication of tensors with scalar

A7 = A1 * 2 
print("Multiplication of tensor A1 with scalar 2 is: ", A7)

#2.6 Division of tensors with scalar
A8 = A1 / 2
print("Division of tensor A1 with scalar 2 is: ", A8)

Multiplication of tensor A1 with scalar 2 is:  tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])
Division of tensor A1 with scalar 2 is:  tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000],
        [3.5000, 4.0000, 4.5000]])


In [15]:
#2.7 Division of tensors (Elementwise)

A9 = A2 / A1
print("Division of two tensors A2 and A1 is: ", A9)

Division of two tensors A2 and A1 is:  tensor([[9.0000, 4.0000, 2.3333],
        [1.5000, 1.0000, 0.6667],
        [0.4286, 0.2500, 0.1111]])


In [16]:
#2.8 Broadcasting

A10 = torch.tensor([1, 2, 3])
print(A10.shape)
A11 = torch.tensor([100])
print(A11.shape)
A12 = A10 + A11
print("Broadcasting of two tensors A10 and A11 is: ", A12)

#2.9 Broadcasting with scalar

A13 = A10 + 500     
print("Broadcasting of tensor A10 with scalar 100 is: ", A13)

#2.10 Broadcasting with different shapes

A14 = torch.tensor([[1, 2, 3]])
print(A14.shape)
A15 = torch.tensor([[10], [20], [30]])
print(A15.shape)
A16 = A14 + A15
print("Broadcasting of two tensors A14 and A15 with different shapes is: ", A16)


torch.Size([3])
torch.Size([1])
Broadcasting of two tensors A10 and A11 is:  tensor([101, 102, 103])
Broadcasting of tensor A10 with scalar 100 is:  tensor([501, 502, 503])
torch.Size([1, 3])
torch.Size([3, 1])
Broadcasting of two tensors A14 and A15 with different shapes is:  tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
